apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: varnish-operator
  template:
    metadata:
      labels:
        name: varnish-operator
    spec:
      serviceAccountName: varnish-operator
      containers:
        - name: varnish-operator
          image: camptocamp/varnish-operator
          command:
          - varnish-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "varnish-operator"
